import type { Metadata } from "next";
import {Baloo_Bhai_2} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const baloobhai2 = Baloo_Bhai_2({
  subsets:['latin','latin-ext'],
  weight:['400','500','600','700','800'],
  style:['normal']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${baloobhai2.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
